services:
  mlbserver:
    image: tonywagner/mlbserver:latest
    container_name: mlbserver
    environment:
      - TZ=America/New York
      - account_username=your.account.email@example.com
      - account_password=youraccountpassword
      #- fav_teams=AZ,BAL
      #- http_root=/mlbserver
      #- debug=false
      #- multiview_path=
      #- ffmpeg_path=
      #- ffmpeg_encoder=
      #- page_username=
      #- page_password=
      #- content_protect=
      #- gamechanger_delay=0
      #- PUID=1000
      #- PGID=1000
    ports:
      - 9999:9999
    volumes:
      - /path/to/your/desired/local/mlbserver/persistent/data/directory:/mlbserver/data_directory